model_name_or_path: /mnt/yinilin/yinilin/models/vicuna-7b-v1.5
version: v0
tune_mm_mlp_adapter: True
pretrain_mm_mlp_adapter: null
mm_projector_type: linear
bert_type: raw_bert_layer:2
compress_type: mean
bert_path: /mnt/yinilin/yinilin/models/bert-base-uncased